### ISSUE TITLE
[6h] Shortcode teaser-news 

### ISSUE THREAD

**Issue by zufrieden** [epfl-si/wp-theme-2018#10]
- [x] Doc https://github.com/epfl-idevelop/doc-epfl-antistatique/blob/master/shortcodes/epfl_shortcode_news.md
- [x] https://epfl-idevelop.github.io/elements/#/organisms/news
- [x] listing
- [x] basic teaser
- [ ] Press release
- [ ] Distinction

**Comment by jdelasoie** [comment]
Fermeture de l'issue car doit passer par https://epfl-webvolution.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=WEBEVOL
