### ISSUE TITLE
Problèmes d'affichage sur la page 404

### ISSUE THREAD

**Issue by williambelle** [epfl-si/wp-theme-2018#229]
Tablet             | Mobile
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPad (7th generation) - 2020-03-08 at 20 26 06](https://user-images.githubusercontent.com/2843501/76189776-d1929c80-61db-11ea-901e-d953dbb98681.png) | ![Screenshot_1583689040](https://user-images.githubusercontent.com/2843501/76189683-985a2c80-61db-11ea-8dff-8bf399c52bf2.png)

**Comment by jdelasoie** [comment]
Should be fine
