### ISSUE TITLE
[Memento] Label "Just finished" - incorrect si pas de end_time sur un event

### ISSUE THREAD

**Issue by obieler** [epfl-si/wp-theme-2018#237]
**Concerne:** shortcode de Memento
**Description:** mauvais label "Just finished" si la end_date est du jour ET (end_date + end_time) > now().
**Problème:** end_time n'est pas un champ obligatoire pour un event. Seuls la start_date et end_date sont obligatoires.

![Selection_091](https://user-images.githubusercontent.com/24526380/64120962-e0684480-cd9d-11e9-8d46-22f8a28b6543.png)

**Comment by GregLeBarbar** [comment]
Corrigé => PR https://github.com/epfl-si/wp-gutenberg-epfl/pull/209
