### ISSUE TITLE
[Memento] Affichage des dates et heures pas au point

### ISSUE THREAD

**Issue by obieler** [epfl-si/wp-theme-2018#239]
Il faut adapter l'affichage des caractère de séparation "-" ">" selon les date et heures de l’événement:
![Selection_093](https://user-images.githubusercontent.com/24526380/64121790-18708700-cda0-11e9-8f55-16cdb9489c2a.png)

Attention, seuls les dates de début et fin sont obligatoirement renseignés. Les heures de début et fin sont optionnelles.

**Voici des exemples d'affichage côté Memento:**

1) date début et fin différente, avec heure de début et heure de fin
2) date début et fin pareil, avec heure de début et heure de fin
3) date début et fin pareil, avec heure de début mais pas d'heure de fin

![Selection_092](https://user-images.githubusercontent.com/24526380/64121817-26260c80-cda0-11e9-9c3e-340b72810edf.png)

**Comment by GregLeBarbar** [comment]
Corrigé PR https://github.com/epfl-si/wp-gutenberg-epfl/pull/209
