### ISSUE TITLE
Intégrer les popover sur les images

### ISSUE THREAD

**Issue by knuch** [epfl-si/wp-theme-2018#79]
là où cela fait du sens (principalement partout où les images proviennent de wordpress, et donc peuvent avoir des métadonnées/descriptions intéressantes, intégrer le bouton popover qu'on peut trouver ici: https://epfl-idevelop.github.io/elements/#/molecules/cover

et penser à aussi saisir les données provenant de l'image and les attributs `alt` des images (a11y)

**Comment by jdelasoie** [comment]
Fermeture de l'issue car doit passer par https://epfl-webvolution.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=WEBEVOL
