### ISSUE TITLE
Problème menu lors la mise à jour du thème

### ISSUE THREAD

**Issue by lvenries** [epfl-si/wp-theme-2018#81]
Chaque fois que nous mettons à jour le thème, la coche primay language (sous Display location) dans le menu disparait. Du coup le breadcrum et le menu et le bouton browse sont cassé. Il faut ajouter manuellement la choche pour que cela fonctionne à nouveau

**Comment by zufrieden** [comment]
Je n'arrive pas à reproduire le bug sur notre instance. Avec les étapes suivantes :

1. Thèmes, Téléverser un nouveau thème
2. Dans Apparence/Menu, Réglage du menu, les emplacements sont identiques

**Comment by lvenries** [comment]
Si tu as un menu en FR et EN et la coche primay FR ou EN (sous Display location) dans chaque menu, les coches disparaissent lors de l'installation du thème.

**Comment by zufrieden** [comment]
Est-ce que ce serait lié à ManageWP ?

Car sur une instance wordpress neuve, je fais les opération suivante :
- Téléverser le thème
- Changer de thème, sélectionner un autre thème, puis revenir à celui de l'EPFL

Dans tous les cas, les 2 menus sont toujours actifs. 

En soit la définition de la région, du menu et du lien avec la langue est définie en DB et n'est pas supprimé chez moi.

Est-ce que tu peux tester sans passer par l'outil de gestion d'instance ? Pour voir si tu as aussi le même bug.

**Comment by knuch** [comment]
@lvenries j'ai pu reproduire le problème, lorsqu'on utilise la commande `wp theme install /Users/.../Desktop/wp-theme-2018-1.2.4.zip --force --activate`, et que le thème change de nom de dossier. 

lorsque la ligne de commande donne un warning `Warning: The 'Epfl' theme is already active.`, les menus sont toujours bien attribués.

Lorsque la ligne de commande output `Success: Switched to 'Epfl' theme.`, dans ce cas les liens sont perdus.

J'investigue pour trouver une solution

**Comment by knuch** [comment]
@lvenries J'ai publié un fix sur la branche dev. 

Comportement:

> si sur l'instance wordpress actuelle, aucun menu n'est attribués à la location `primary` du thème, le script va filtrer les menus, chercher ceux qui ont les titres `en` ou `fr` (en minuscule) et les ré-attribuer à la langue correspondante. Ce script se lance lors du premier affichage de page sur le site (fronted OU backend)

**Comment by jdelasoie** [comment]
N'est plus d'actualité
